# -*- coding: utf-8 -*-
"""将中文字体按 unicode-range 分块生成 woff2 子集 + @font-face CSS。

用法:
    python scripts/split-fonts.py <源字体.ttf> <输出目录> <font-family名> [--chunk 0x400]
"""
import os
import sys

from fontTools import subset


def parse_hex_int(s):
    return int(s, 16)


def build_ranges(chunk_size):
    """返回 [(name, [(start, end), ...]), ...]，覆盖 ASCII、CJK 标点、全角与 GB 汉字区。"""
    ranges = []
    # 拉丁/数字/基础标点 + 常见扩展
    ranges.append(("latin", [(0x0020, 0x007E), (0x00A0, 0x00FF), (0x2010, 0x2027),
                             (0x2026, 0x2026), (0x2030, 0x205E), (0x20AC, 0x20AC),
                             (0x2190, 0x21FF)]))
    # CJK 符号/标点、全角、带圈数字等
    ranges.append(("cjk-sym", [(0x3000, 0x303F), (0x3200, 0x32FF), (0x3300, 0x33FF),
                               (0xFF00, 0xFFEF), (0x2000, 0x200F), (0x25A0, 0x25FF),
                               (0x2600, 0x27BF), (0x2E80, 0x2EFF), (0x31C0, 0x31EF)]))
    # 汉字 U+4E00 – U+9FFF 按块切分
    start = 0x4E00
    end = 0x9FFF
    idx = 0
    cur = start
    while cur <= end:
        e = min(cur + chunk_size - 1, end)
        ranges.append((f"cjk-{idx:02d}", [(cur, e)]))
        cur += chunk_size
        idx += 1
    return ranges


def subset_font(src, out_dir, family, chunk_size):
    os.makedirs(out_dir, exist_ok=True)
    css_lines = []
    css_lines.append(f"/* Generated by scripts/split-fonts.py from {os.path.basename(src)} */")

    ranges = build_ranges(chunk_size)
    files = []
    for name, rng in ranges:
        unicodes = ",".join(f"U+{a:04X}-{b:04X}" for a, b in rng)
        out_name = f"{family}-{name}.woff2"
        out_path = os.path.join(out_dir, out_name)
        args = [
            src,
            f"--unicodes={unicodes}",
            "--flavor=woff2",
            "--layout-features=*",
            "--no-hinting",
            "--desubroutinize",
            f"--output-file={out_path}",
        ]
        print(f"[subset] {out_name} <- {unicodes}", flush=True)
        subset.main(args)

        # 构建 unicode-range 字符串（CSS 语法）
        ur = ",".join(
            f"U+{a:04X}-{b:04X}" if b > a else f"U+{a:04X}" for a, b in rng
        )
        files.append((out_name, ur))

    # 生成 CSS：一个 @font-face 对应一个块，全部指向同一 family
    css_lines.append(f"@font-face {{")
    css_lines.append(f"  font-family: '{family}';")
    css_lines.append(f"  font-style: normal;")
    css_lines.append(f"  font-weight: 400;")
    css_lines.append(f"  font-display: swap;")
    css_lines.append(f"  src: url('{files[0][0]}') format('woff2');")
    css_lines.append(f"  unicode-range: {files[0][1]};")
    css_lines.append(f"}}")
    for name, ur in files[1:]:
        css_lines.append(f"@font-face {{")
        css_lines.append(f"  font-family: '{family}';")
        css_lines.append(f"  font-style: normal;")
        css_lines.append(f"  font-weight: 400;")
        css_lines.append(f"  font-display: swap;")
        css_lines.append(f"  src: url('{name}') format('woff2');")
        css_lines.append(f"  unicode-range: {ur};")
        css_lines.append(f"}}")

    css_path = os.path.join(out_dir, "index.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write("\n".join(css_lines) + "\n")
    print(f"[css] wrote {css_path}", flush=True)


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)
    src = sys.argv[1]
    out_dir = sys.argv[2]
    family = sys.argv[3]
    chunk = 0x400
    if "--chunk" in sys.argv:
        chunk = parse_hex_int(sys.argv[sys.argv.index("--chunk") + 1])
    subset_font(src, out_dir, family, chunk)


if __name__ == "__main__":
    main()
